build:
    environment:
        python: 2.7.7

    tests:
        override:
            -
                command: 'py.test --cov trains.py'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
