language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly" # currently points to 3.7-dev

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - py.test --cov trains.py
  #- python -m pytest ${TRAVIS_BUILD_DIR}/tests --cov=${TRAVIS_BUILD_DIR}/tablebuilder

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
  - coveralls
